# issuer.isso = cookie token from UI (browser)
# issuer.oidc = bearer token from API (header)
# issuer.pesys = bearer token from other places (servicebruker) (header)

#AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}

METRICS_REQUESTFILTER_ENABLE: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  metrics:
    web:
      server:
        auto-time-requests: true

#Embedded tomcat
server:
  servlet:
    session:
      timeout: '120s'
  error:
    include-message: always
