kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-dodsmelding-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: dodsmelding-dev #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: eessi-pensjon-dodsmelding-q2
          namespace: eessipensjon
          cluster: dev-gcp
      external:
        - host: pensjon-q2.pensjon-pen-q2
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: pensjon-psak-q2.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: pensjon-psak-q2
          namespace: pensjon-q2
          cluster: dev-gcp
  gcp:
    buckets:
      - name: eessi-pensjon-dodsmelding-q2
      - name: eessi-pensjon-opprettet-h070-q2

  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ENV
      value: q2

    - name: GCP_BUCKET_UTL_YTELSE
      value: eessi-pensjon-dodsmelding-q2

    - name: GCP_H070_OPPRETTET
      value: eessi-pensjon-opprettet-h070-q2

    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q2.intern.dev.nav.no/cpi

    - name: EUX_RINA_API_V5_URL
      value: https://eux-rina-api-q2.intern.dev.nav.no/v5

    - name: PESYS_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/api/eessi/v2

    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql

    - name: SAF_HENTDOKUMENT_URL
      value: https://saf-q2.dev-fss-pub.nais.io/rest/hentdokument

    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql

    #AZURE
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-gcp.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: AZURE_APP_PEN_CLIENT_ID
      value: dev-fss.pensjon-q2.pensjon-pen-q2

    #KAFKA
    - name: KAFKA_PDLHENDELSE_TOPIC
      value: pdl.leesah-v1
    - name: KAFKA_GROUP_ID
      value: eessi-pensjon-dodsmelding-q2


  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-dodsmelding-q2.intern.dev.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 700Mi
    requests:
      cpu: 200m
      memory: 512Mi

